/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
*/
var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// main.ts
var main_exports = {};
__export(main_exports, {
  default: () => MobileStatsPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian = require("obsidian");
var STOP_WORDS = /* @__PURE__ */ new Set([
  "\u56E0\u6B64",
  "\u901A\u8FC7",
  "\u53EF\u4EE5",
  "\u4E00\u4E2A",
  "\u6CA1\u6709",
  "\u6211\u4EEC",
  "\u4EC0\u4E48",
  "\u8FD9\u4E2A",
  "\u5982\u679C\u662F",
  "\u600E\u4E48",
  "\u5982\u679C",
  "\u53EF\u4EE5\u8BF4",
  "\u8FD9\u6837",
  "\u5F88\u591A",
  "\u975E\u5E38",
  "\u8FDB\u884C",
  "\u7136\u540E",
  "\u53EF\u80FD",
  "\u56E0\u4E3A",
  "\u6240\u4EE5",
  "\u5404\u4F4D",
  "\u8C22\u8C22",
  "\u7531\u4E8E",
  "\u5176\u5B9E",
  "\u53EA\u8981",
  "\u76EE\u524D",
  "\u5F00\u59CB",
  "\u81EA\u5DF1",
  "\u5C31\u662F",
  "\u9700\u8981",
  "\u95EE\u9898",
  "\u4EA7\u751F",
  "\u4F7F\u7528",
  "\u53D1\u73B0",
  "\u8FD9\u79CD",
  "\u90A3\u4E9B",
  "\u4E5F\u662F",
  "\u4E00\u6837",
  "\u77E5\u9053",
  "\u89C9\u5F97",
  "\u65F6\u5019"
]);
var FALLBACK_WORDS = [
  { word: "\u6DB2\u51B7\u6280\u672F", value: 10 },
  { word: "\u70ED\u7BA1\u7406", value: 9 },
  { word: "\u81EA\u52A8\u5316", value: 9 },
  { word: "\u7CFB\u7EDF\u67B6\u6784", value: 8 },
  { word: "\u50A8\u80FD", value: 8 },
  { word: "\u670D\u52A1\u5668", value: 7 },
  { word: "\u5DE5\u4F5C\u6D41", value: 7 },
  { word: "\u6570\u636E\u5206\u6790", value: 6 },
  { word: "\u6027\u80FD\u6D4B\u8BD5", value: 6 },
  { word: "\u6838\u5FC3\u63A7\u5236", value: 5 },
  { word: "\u7ED3\u6784\u8BBE\u8BA1", value: 5 },
  { word: "\u65B0\u80FD\u6E90", value: 5 },
  { word: "\u6548\u7387\u4F18\u5316", value: 4 },
  { word: "\u89E3\u51B3\u65B9\u6848", value: 4 },
  { word: "\u7CBE\u5BC6\u52A0\u5DE5", value: 4 },
  { word: "\u5DE5\u827A", value: 3 },
  { word: "\u8282\u70B9", value: 3 },
  { word: "\u7B56\u7565", value: 3 },
  { word: "\u77E9\u9635", value: 2 },
  { word: "\u53C2\u6570", value: 2 },
  { word: "\u6A21\u578B", value: 2 }
];
var cssVars = {
  textNormal: "#333333",
  textMuted: "#666666",
  textFaint: "#999999"
};
var WordSphereDecorativeEngine = class {
  constructor(container, radius) {
    this.width = 0;
    this.height = 0;
    this.tags = [];
    this.velocityX = 25e-4;
    this.velocityY = 25e-4;
    this.animationFrameId = 0;
    this.isActive = true;
    // 核心视觉重心偏移：不改DOM导致跳动，直接在渲染层将画面往下推！
    this.visualOffsetY = 15;
    // 丝滑优化：离屏 Canvas 预渲染 + 帧间隔控制
    this.frameCount = 0;
    this.targetFPS = 60;
    this.frameInterval = 1e3 / 60;
    this.lastFrameTime = 0;
    // 缓存样式字符串，减少 DOM 操作
    this.styleCache = /* @__PURE__ */ new Map();
    this.container = container;
    this.radius = radius;
    this.canvas = document.createElement("canvas");
    this.canvas.style.position = "absolute";
    this.canvas.style.top = "0";
    this.canvas.style.left = "0";
    this.canvas.style.width = "100%";
    this.canvas.style.height = "100%";
    this.canvas.style.willChange = "transform";
    this.container.appendChild(this.canvas);
    const context = this.canvas.getContext("2d", { alpha: true });
    if (!context)
      throw new Error("Canvas 2D context not supported");
    this.ctx = context;
    this.handleResize();
    const RO = window.ResizeObserver;
    if (RO) {
      const observer = new RO(() => this.handleResize());
      observer.observe(this.container);
    }
    this.updateCssVars();
  }
  updateCssVars() {
    const style = getComputedStyle(document.body);
    cssVars.textNormal = style.getPropertyValue("--text-normal").trim() || "#333333";
    cssVars.textMuted = style.getPropertyValue("--text-muted").trim() || "#666666";
    cssVars.textFaint = style.getPropertyValue("--text-faint").trim() || "#999999";
  }
  handleResize() {
    const rect = this.container.getBoundingClientRect();
    if (rect.width === 0 || rect.height === 0)
      return;
    const safeRadiusWidth = rect.width / 2 - 20;
    const safeRadiusHeight = rect.height / 2 - 20;
    let newRadius = Math.min(safeRadiusWidth, safeRadiusHeight);
    newRadius = Math.max(newRadius, 40);
    if (this.radius > 0 && this.tags.length > 0 && this.radius !== newRadius) {
      const scaleFactor = newRadius / this.radius;
      this.tags.forEach((tag) => {
        tag.lx *= scaleFactor;
        tag.ly *= scaleFactor;
        tag.lz *= scaleFactor;
      });
    }
    this.radius = newRadius;
    const dpr = window.devicePixelRatio || 1;
    this.canvas.width = rect.width * dpr;
    this.canvas.height = rect.height * dpr;
    this.ctx.scale(dpr, dpr);
    this.width = rect.width;
    this.height = rect.height;
  }
  addTag(tagEl) {
    tagEl.style.position = "absolute";
    tagEl.style.left = "50%";
    tagEl.style.top = "50%";
    tagEl.style.willChange = "transform, opacity";
    tagEl.style.zIndex = "10";
    tagEl.style.backfaceVisibility = "hidden";
    tagEl.style.perspective = "1000px";
    this.tags.push({
      el: tagEl,
      lx: 0,
      ly: 0,
      lz: 0,
      zRatio: 0,
      x2d: 0,
      y2d: 0
    });
    this.container.appendChild(tagEl);
  }
  initPositions() {
    const total = this.tags.length;
    if (total === 0)
      return;
    const offset = 2 / total;
    const increment = Math.PI * (3 - Math.sqrt(5));
    this.tags.forEach((tag, i) => {
      const y = i * offset - 1 + offset / 2;
      const r = Math.sqrt(1 - y * y);
      const phi = i * increment;
      tag.lx = Math.cos(phi) * r * this.radius;
      tag.ly = y * this.radius;
      tag.lz = Math.sin(phi) * r * this.radius;
      tag.zRatio = tag.lz / this.radius;
    });
  }
  startAnimation() {
    if (this.tags.length === 0)
      return;
    this.initPositions();
    this.updateCssVars();
    const animate = (timestamp) => {
      if (!this.isActive)
        return;
      const elapsed = timestamp - this.lastFrameTime;
      if (elapsed < this.frameInterval) {
        this.animationFrameId = window.requestAnimationFrame(animate);
        return;
      }
      this.lastFrameTime = timestamp - elapsed % this.frameInterval;
      const cx = this.width / 2;
      const cy = this.height / 2 + this.visualOffsetY;
      const cosY = Math.cos(this.velocityY);
      const sinY = Math.sin(this.velocityY);
      const cosX = Math.cos(this.velocityX);
      const sinX = Math.sin(this.velocityX);
      this.tags.forEach((tag) => {
        const x1 = tag.lx * cosY - tag.lz * sinY;
        const z1 = tag.lz * cosY + tag.lx * sinY;
        const y1 = tag.ly * cosX - z1 * sinX;
        const z2 = z1 * cosX + tag.ly * sinX;
        tag.lx = x1;
        tag.ly = y1;
        tag.lz = z2;
        tag.zRatio = z2 / this.radius;
        tag.x2d = tag.lx;
        tag.y2d = tag.ly;
      });
      this.ctx.clearRect(0, 0, this.width, this.height);
      const neutralLineColor = "128, 128, 128";
      const backItems = [];
      const frontItems = [];
      this.tags.forEach((tag) => {
        if (tag.lz >= 0) {
          frontItems.push(tag);
        } else {
          backItems.push(tag);
        }
      });
      backItems.forEach((item) => {
        this.drawConnectionLine(cx, cy, item, neutralLineColor);
      });
      this.ctx.beginPath();
      this.ctx.arc(cx, cy, 2, 0, Math.PI * 2);
      this.ctx.fillStyle = cssVars.textNormal;
      this.ctx.fill();
      frontItems.forEach((item) => {
        this.drawConnectionLine(cx, cy, item, neutralLineColor);
      });
      const radius2 = this.radius * 2;
      this.tags.forEach((tag) => {
        const tagEl = tag.el;
        let baseOpacity;
        let blur;
        let color;
        const zr = tag.zRatio;
        if (zr > 0.4) {
          baseOpacity = 0.9;
          blur = 0;
          color = cssVars.textNormal;
        } else if (zr > 0) {
          baseOpacity = 0.4 + 0.5 * (zr / 0.4);
          blur = 0;
          color = cssVars.textMuted;
        } else {
          baseOpacity = 0.1 + 0.3 * ((zr + 1) / 1);
          blur = Math.min(2, Math.abs(zr) * 2);
          color = cssVars.textFaint;
        }
        const depthScale = 0.6 + 0.5 * ((this.radius + tag.lz) / radius2);
        const transform = `translate3d(-50%, -50%, 0) translate3d(${tag.x2d}px, ${tag.y2d + this.visualOffsetY}px, 0) scale(${depthScale})`;
        tagEl.style.transform = transform;
        tagEl.style.opacity = baseOpacity.toString();
        tagEl.style.color = color;
        tagEl.style.filter = blur > 0 ? `blur(${blur}px)` : "";
        tagEl.style.zIndex = Math.round(tag.lz + this.radius).toString();
      });
      this.animationFrameId = window.requestAnimationFrame(animate);
    };
    this.animationFrameId = window.requestAnimationFrame(animate);
  }
  drawConnectionLine(cx, cy, item, neutralRGB) {
    const zr = item.zRatio;
    let depthOpacity = 0;
    let depthWidth = 0.3;
    if (zr > 0) {
      depthOpacity = 0.05 + 0.12 * zr;
      depthWidth = 0.3 + 0.3 * zr;
    } else {
      depthOpacity = 0.05 * (1 - Math.abs(zr));
      depthWidth = 0.3;
    }
    if (depthOpacity <= 0)
      return;
    this.ctx.beginPath();
    this.ctx.moveTo(cx, cy);
    this.ctx.lineTo(cx + item.x2d, cy + item.y2d);
    this.ctx.lineWidth = Math.max(0.1, depthWidth);
    this.ctx.strokeStyle = `rgba(${neutralRGB}, ${depthOpacity})`;
    this.ctx.stroke();
  }
  destroy() {
    this.isActive = false;
    if (this.animationFrameId)
      window.cancelAnimationFrame(this.animationFrameId);
  }
};
async function analyzeDecorativeData(app) {
  try {
    const files = app.vault.getMarkdownFiles();
    if (files.length === 0)
      return FALLBACK_WORDS;
    const largestFiles = files.sort((a, b) => b.stat.size - a.stat.size).slice(0, 20);
    const wordData = /* @__PURE__ */ new Map();
    for (const file of largestFiles) {
      const content = await app.vault.cachedRead(file);
      const matches = content.match(/[\u4e00-\u9fa5]{2,5}/g) || [];
      for (const w of matches) {
        if (STOP_WORDS.has(w))
          continue;
        wordData.set(w, (wordData.get(w) || 0) + 1);
      }
    }
    const results = Array.from(wordData.entries()).sort((a, b) => b[1] - a[1]).slice(0, 32).map(([word, value]) => ({ word, value }));
    if (results.length < 15)
      return FALLBACK_WORDS;
    return results;
  } catch (e) {
    return FALLBACK_WORDS;
  }
}
var MobileStatsPlugin = class extends import_obsidian.Plugin {
  constructor() {
    super(...arguments);
    this.sphereEngine = null;
    this.injectedContainer = null;
    this.cachedWords = null;
    // 丝滑驻留的核心监听器
    this.mutationObserver = null;
    this.currentObserverTarget = null;
  }
  async onload() {
    this.app.workspace.onLayoutReady(async () => {
      this.cachedWords = await analyzeDecorativeData(this.app);
      this.observeAndInject();
    });
    this.registerEvent(this.app.workspace.on("layout-change", () => {
      this.observeAndInject();
    }));
    this.registerEvent(this.app.workspace.on("file-open", () => {
      this.observeAndInject();
    }));
  }
  async onunload() {
    if (this.sphereEngine)
      this.sphereEngine.destroy();
    if (this.injectedContainer)
      this.injectedContainer.remove();
    if (this.mutationObserver)
      this.mutationObserver.disconnect();
    this.cachedWords = null;
  }
  // 零延迟自愈构建方法
  observeAndInject() {
    try {
      const allLeaves = this.app.workspace.getLeaves();
      console.log("[MindDrift] All leaves:", allLeaves.map((l) => l.view.constructor.name));
      const fileExplorerLeaves = this.app.workspace.getLeavesOfType("file-explorer");
      console.log("[MindDrift] file-explorer leaves:", fileExplorerLeaves.length);
      if (fileExplorerLeaves.length === 0)
        return;
      const fileExplorerContainer = fileExplorerLeaves[0].view.containerEl;
      const navContainer = fileExplorerContainer.querySelector(".nav-files-container");
      console.log("[MindDrift] nav-container:", !!navContainer);
      if (!navContainer)
        return;
      if (!this.injectedContainer) {
        this.buildContainer(navContainer);
      }
      if (!navContainer.contains(this.injectedContainer)) {
        navContainer.appendChild(this.injectedContainer);
      }
      if (this.currentObserverTarget !== navContainer) {
        if (this.mutationObserver)
          this.mutationObserver.disconnect();
        this.mutationObserver = new MutationObserver(() => {
          if (this.injectedContainer && !navContainer.contains(this.injectedContainer)) {
            navContainer.appendChild(this.injectedContainer);
          }
        });
        this.mutationObserver.observe(navContainer, { childList: true });
        this.currentObserverTarget = navContainer;
      }
    } catch (e) {
      console.error("[MindDrift] Error: ", e);
    }
  }
  // 独立出构建 UI 的方法，只在插件最初加载时跑一次
  buildContainer(navContainer) {
    if (this.sphereEngine)
      this.sphereEngine.destroy();
    this.injectedContainer = document.createElement("div");
    this.injectedContainer.className = "mobile-parasitic-heatmap";
    this.injectedContainer.setAttribute("style", `
            width: 100%;
            height: 240px; 
            margin: 15px 0;
            display: flex;
            flex-shrink: 0; 
            justify-content: center;
            align-items: center;
            position: relative;
            background-color: transparent;
            pointer-events: none;
        `);
    const heatmapDiv = this.injectedContainer.createDiv({
      attr: { style: "width: 100%; height: 100%; display: flex; justify-content: center; align-items: center; overflow: hidden; position: relative;" }
    });
    navContainer.appendChild(this.injectedContainer);
    const heatmapWords = this.cachedWords || FALLBACK_WORDS;
    if (heatmapWords.length === 0)
      return;
    const maxWordCount = heatmapWords[0].value;
    const baseRadius = Math.max(heatmapDiv.clientWidth / 2 * 0.75, 55);
    this.sphereEngine = new WordSphereDecorativeEngine(heatmapDiv, baseRadius);
    heatmapWords.forEach(({ word, value }) => {
      const wordEl = document.createElement("div");
      wordEl.innerText = word;
      const fontSize = Math.max(11, Math.min(21, 11 + value / maxWordCount * 10));
      const fontWeight = value > maxWordCount * 0.5 ? "700" : "400";
      wordEl.setAttr("style", `
                font-family: "SimSun", "STSong", "Songti SC", serif;
                font-size: ${fontSize}px;
                font-weight: ${fontWeight};
                letter-spacing: 0.5px;
                white-space: nowrap;
                user-select: none;
                transform-origin: center center;
            `);
      this.sphereEngine.addTag(wordEl);
    });
    this.sphereEngine.startAnimation();
  }
};
